language: bash

dist: focal

services: docker

os: linux

arch: amd64

script:
  - git clone --single-branch --branch enterprise-2.2 https://github.com/rpsene/travis-build.git
  - cd ./travis-build
  - docker build -t travis-build --build-arg GITHUB_OAUTH_TOKEN="$GH_TOKEN" .
  - docker tag travis-build:latest quay.io/rpsene/travis-build:latest
  - docker login -u="$QUAY_USER" -p="$QUAY_PWD" quay.io
  - docker push quay.io/rpsene/travis-build:latest
